# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-04 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.CharField(max_length=1024, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=1024)),
                ('price', models.CharField(max_length=50)),
                ('seller_info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MobileDeUrlPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2014)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='cars.Car')),
            ],
        ),
    ]
