# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-31 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
