# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('subscribe_email', models.EmailField(max_length=254)),
                ('update_interval', models.IntegerField()),
                ('interval_measure', models.CharField(choices=[('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks')], max_length=16)),
                ('is_active', models.BooleanField(default=False)),
                ('next_run_date', models.DateTimeField(null=True)),
                ('number_of_times_scraped', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'SearchUrl',
                'verbose_name_plural': 'SearchUrls',
            },
        ),
    ]
