# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchurl',
            name='title',
            field=models.CharField(default='default', max_length=128),
            preserve_default=False,
        ),
    ]
