# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-05 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20160131_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchurl',
            name='number_of_emails_sent',
            field=models.IntegerField(default=0),
        ),
    ]
